feature/running-line: init
Leroyjs/color-department pull request #16
Opened 2022-08-07 18:16 UTC by Kaigarodov

⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡰⠋⠉⠙⣟⠻⣶⢄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⠴⠒⣆⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣼⣁⣤⠤⠄⠚⠳⠈⢢⠙⢦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣤⣶⣊⣁⠀⠀⠘⡆⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⣰⡟⠉⣠⠟⠁⠀⠀⣀⠠⣵⡀⠉⢉⣭⡽⠛⠉⠁⠀⠁⠑⠒⠲⠤⣀⠀⢀⠤⢲⡿⠫⠟⢋⡟⠁⠀⠀⠀⠸⡀
⠀⠀⠀⠀⠀⠀⠀⠀⢠⡏⢠⡞⣥⢄⡤⠒⠉⠀⠀⢀⡭⢤⡞⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⠄⠉⠥⡔⠁⠀⠀⠀⠈⠉⢉⡽⠆⠀⠀⢇
⠀⠀⠀⠀⠀⠀⠀⠀⣼⡇⠀⡠⠛⡪⠂⠀⢀⠀⡰⠃⣰⡟⠁⠀⠀⠀⠀⠀⠀⠀⠀⡴⠋⢠⠀⠀⠀⠙⢤⡄⠀⠀⠀⠸⣷⠄⠀⠀⠀⢸
⠀⠀⠀⠀⠀⠀⠀⠀⣿⣠⠊⢠⠞⠀⠀⢠⠋⡸⠁⡼⡇⠀⠀⠀⠀⠀⠀⠀⠀⢠⠊⠀⣠⠃⡄⠀⠀⠀⢄⠘⣦⡀⠀⠀⠘⡆⠀⠀⠀⢸
⠀⠀⠀⠀⠀⠀⠀⣰⢟⠅⡠⠃⡄⠀⢠⠇⠀⠁⡜⢀⠇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡴⢹⠀⡃⠀⠀⠀⢸⡄⠀⠙⢆⢢⣸⠇⠀⠀⠀⠸
⠀⠀⠀⠀⠀⢀⠜⢡⣫⡾⠁⡜⠀⢀⣾⠀⠀⡜⠐⢸⠀⡀⠀⠀⠀⠀⠀⠀⠀⣠⡟⠁⠈⡾⣇⠀⠀⡄⠐⣿⡀⠀⠈⠉⠙⣆⠀⠀⠀⢄
⠀⠀⠀⠀⡴⠋⣰⠟⢡⠃⢰⠁⢠⠏⢹⠀⡼⠀⣀⣨⡟⠉⠀⠀⠀⠀⠀⠈⣻⠟⠲⢤⡀⣇⣿⡀⠀⢱⠀⢹⣧⠀⠀⠀⠀⢻⣆⠀⠀⠀
⠀⠀⢀⣾⠟⣿⠏⠀⡎⢀⡇⠀⡞⢂⣼⣼⡗⠛⠉⠀⢧⠀⠀⠀⠀⠀⢰⢠⠃⠀⠀⠀⠈⢻⣧⣧⠀⠈⡆⠘⣿⡀⠀⠀⠀⠀⠏⠆⠀⠀
⠀⣠⣿⠏⣰⡏⠀⠀⣇⡾⡁⡸⠀⠀⠀⠙⠓⠀⠐⠒⠺⣧⡀⠀⠀⢠⣿⡏⠀⠀⠄⠀⠀⠘⣿⠘⡆⠀⡇⠀⣿⠃⠀⠀⠀⠀⠀⠀⠀⠀
⣰⣿⡏⠀⢿⡇⠀⠀⣿⢀⣷⡇⠀⢀⣀⡀⣀⣀⣀⢀⡀⠈⠛⢄⡀⡼⣿⠀⠠⠤⢀⣀⠀⠀⠹⡇⠹⡀⢃⠀⢸⠆⠀⠀⠀⠀⠀⠀⠀⠀
⡏⡼⠀⠀⣸⠁⠀⠀⠙⣺⣈⣳⣶⣞⣛⣋⣉⠉⠻⡿⠋⠀⠀⠀⠈⠉⠩⠄⢠⣴⡾⠷⠾⣵⣄⡹⣄⣣⣾⠀⢸⠀⠀⡀⠀⠀⠀⠀⠀⠀
⣸⠁⠀⠀⡇⠀⠀⢀⠄⡏⠻⢯⣈⣦⣤⡽⣍⠤⣶⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠦⣙⣦⣄⡠⠭⣿⣿⣿⢹⡄⠂⠀⢰⠃⠀⠀⠀⠀⠀⠀
⠃⠀⠀⢸⠀⠀⠀⡜⢸⡇⠀⠀⠉⠉⢉⣀⢤⡴⠛⠒⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠉⠲⣀⡛⠁⠽⠿⡇⠀⢠⠇⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⡞⠀⠀⣰⢃⣾⠆⠀⠀⠀⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠁⠀⠀⡼⠀⢀⠎⠀⠀⠀⡞⠀⠀⠀⠀
⠀⠀⢠⡇⠀⠀⣟⣼⢹⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣀⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢰⠃⢀⠎⠀⠀⠀⢸⣧⠀⠀⠀⠀
⠀⠀⣾⠁⠀⢠⣿⡏⢹⠀⠀⠀⠀⠀⠀⠀⠀⢀⡴⠋⣥⣤⣄⣉⡓⢤⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⠇⢠⠏⠀⠀⡄⢀⠋⠻⡇⠀⠀⠀
⠀⢰⣿⠀⠀⢘⣿⣿⣼⡀⠀⠀⠀⠀⠀⠀⠀⢸⣧⣀⣿⣿⣿⣿⣿⣷⣟⣦⠀⠀⠀⠀⠀⠀⠀⣰⠃⡰⠃⠀⠀⡜⠀⡾⠀⢀⡆⠀⠀⠀
⠀⡿⢻⣄⢰⣿⡟⣿⠈⢧⠀⠀⠀⠀⢀⡀⠀⠈⣿⣿⣿⣿⣿⣿⣿⣿⣿⠃⠀⠀⠀⠀⠀⢀⠞⢁⠞⣡⣶⣄⡜⠀⣘⡠⣾⠏⠀⢰⠀⠀
⠀⠇⢸⣿⠀⢹⡿⢿⠂⠈⣧⠀⢀⠖⠉⠈⢱⠀⢿⡿⠉⠀⠈⠁⠀⣹⠇⠀⠀⠀⠀⢀⡴⢋⠀⠀⠀⠛⠓⡶⠀⡘⢁⡔⠁⠀⢠⠃⠀⠀
⠘⠀⠈⣿⡦⢼⡅⠘⡆⣀⣾⣷⡀⠳⢄⣠⠎⠀⠈⢳⣦⣤⣤⡰⠞⠁⠀⠀⠀⢀⡴⢋⣰⠋⠀⠀⠀⢀⡾⢧⣿⠟⡁⠀⢀⢾⠇⠀⠀⠀
⠀⠀⠀⠘⣿⡈⡇⠀⣟⠛⠉⠉⠛⢦⡀⠀⠀⠀⠀⠀⠀⠈⣇⡀⠀⠀⠀⢀⡤⠋⡠⣾⣿⡤⣴⡶⠀⠛⠀⣼⣃⡜⠁⢀⢞⡞⠀⠀⠀⠀
⠀⠀⠀⠀⠹⣧⣱⠼⠛⠁⠀⠀⠀⠀⢹⣦⣄⠀⠀⠀⠀⠀⢸⡇⠀⣠⢖⣩⠔⠋⣠⡋⠁⣀⢋⠀⠀⢀⣾⣿⠏⠀⢀⣞⣾⡇⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠻⣿⣆⠀⠀⠠⠀⣤⣶⣿⣿⣯⠀⢀⣀⠀⠀⠐⠒⣛⣻⠭⡔⠒⢉⠉⠁⠀⢨⢉⡀⢀⡞⣼⠏⠀⢦⣿⠏⢸⠁⠀⠀⠀⠀

2022-08-07 18:41 UTC, Leroyjs commented
За превью лайк

2022-08-08 05:32 UTC, Leroyjs requested changes
А так вроде заебись

2022-08-08 05:32 UTC, Leroyjs commented on components/common/running-line/running-line.jsx
> +    console.log(content)
консоль логи нужно чистить

2022-08-08 05:32 UTC, Leroyjs commented on components/common/running-line/running-line.jsx
> +const separatorText = (
лучше сделать компонентом. Так читабельность будет выше.

И не забудь что компоненты пишутся с большой буквы

const SeparatorText = () => (

2022-08-08 05:32 UTC, Leroyjs commented on components/common/running-line/running-line.style.js
> +    margin: 0 16px;
а шо у нас тут за маржины без функций?

2022-08-08 21:18 UTC, Kaigarodov commented on components/common/running-line/running-line.jsx
> +const SeparatorText = () => (
Переделал в компоненту, но думаю это больше заглушка, хотя можем оставить значением дефолтным

2022-08-08 21:19 UTC, Kaigarodov commented on components/common/running-line/running-line.jsx
> +export const RunningLine = React.memo(({ titles = ['WANT', 'TO', 'SLEEP', 'AND', 'MAC_PRO'], separator = SeparatorText, outline, link, ...props }) => {
Засунул в React.memo вроде сработало
Внутри React.memo есть смысл использовать хук useMemo/useEffect ?

2022-08-08 21:19 UTC, Kaigarodov commented on components/common/running-line/running-line.style.js
> +    ${getCurrentMarginStyle('horizontal', 'sm')}
)

2022-08-08 21:21 UTC, Kaigarodov commented on pages/index.js
> +            </div>
пока заглушка

2022-08-08 21:21 UTC, Kaigarodov commented on components/common/running-line/running-line.jsx
> +            {separator()}
Компонента извне вставляется так ?

2022-08-08 21:25 UTC, merged