feature/footer: first try
Leroyjs/color-department pull request #21
Opened 2022-08-11 19:24 UTC by Kaigarodov

каждый раз, как первый)

2022-08-11 19:38 UTC, Leroyjs requested changes

2022-08-11 19:38 UTC, Leroyjs commented on components/common/fox-logo/fox-logo.jsx
> +export const FoxLogo = (props) => {
нужно обдумать что мы будем делать с свг. Мы будем делать из них компонент или встраивать как-нибудь через лоадер?
@igorTyugaev

2022-08-11 19:38 UTC, Leroyjs commented on components/sections/footer/footer.style.js
> +    margin-bottom: calc(${sizes['desktopLG'].half} * 2);
зачем брать половину и умножать на 2, если можно взять просто целое число?)
Та же есть 1x

2022-08-11 19:38 UTC, Leroyjs commented on components/sections/footer/footer.style.js
> +    background-image: url('./footer-map.png');
а путь до картинки тут разве не через импорт засовываются?

2022-08-11 19:38 UTC, Leroyjs commented on components/sections/footer/footer.style.js
> +    height: ${`calc(${sizes['desktopLG'].half} * 2)`};
calc(${sizes['desktopLG'].half} * 2) === sizes['desktopLG'].1x

2022-08-11 19:38 UTC, Leroyjs commented
lgfm

2022-08-13 06:00 UTC, Kaigarodov commented on components/sections/footer/footer.style.js
> +    margin-bottom: calc(${sizes['desktopLG'].half} * 2);
тупанув

2022-08-13 06:01 UTC, Kaigarodov commented on components/common/fox-logo/fox-logo.jsx
> +export const FoxLogo = (props) => {
через компоненту выглядит удобно, не забудьте обсудить)

2022-08-13 06:01 UTC, Kaigarodov commented on components/sections/footer/footer.style.js
> +    background-image: url('./footer-map.png');
пробовал, у меня не заимпортилось, оставил так т.к. это все равно заглушка и нужна компонента карты

2022-08-13 06:03 UTC, merged