Feature/text blocks
Leroyjs/color-department pull request #22
Opened 2022-08-13 15:32 UTC by SergeiKolesnikovAdd

2022-08-14 09:48 UTC, Kaigarodov commented on components/common/planet/planet.jsx
> +        stroke-width="2"
ставлю очко, что должно быть strokeWidth
(надеюсь не проиграю)

2022-08-14 09:48 UTC, Kaigarodov commented on pages/text-block-test.js
> +export default TextBlocks;
вроде без криминала
за абсолютные величины вроде 185px и 72px Сережа пояснил и сказал, что разберется

2022-08-16 08:26 UTC, SergeiKolesnikovAdd commented on components/sections/intro-about-text-block/intro-about-text-block.jsx
> +      <> </>
поправил

2022-08-16 08:28 UTC, SergeiKolesnikovAdd commented on components/sections/intro-about-text-block/intro-about-text-block.jsx
> +      </PointWrapper>
Он используется, только в одной секции на одной странице. Слишком кастомный. Его основная задача собрать вместе число в кружке и после него.

2022-08-16 08:32 UTC, SergeiKolesnikovAdd commented on components/common/planet/planet.jsx
> +        stroke-width="2"
В данном случае это не пропс, а свг атрибут, который указывает ширину линии, которой отрисован объект. Так что ты проиграл :D

2022-08-16 12:42 UTC, Leroyjs requested changes

2022-08-16 13:43 UTC, SergeiKolesnikovAdd commented on components/sections/intro-about-text-block/intro-about-text-block.jsx
> +          <Caption>01</Caption>
поправил

2022-08-16 13:43 UTC, SergeiKolesnikovAdd commented on components/sections/intro-about-text-block/intro-about-text-block.jsx
> +          <Caption>01</Caption>
поправил

2022-08-16 13:53 UTC, SergeiKolesnikovAdd commented on components/sections/intro-about-text-block/intro-about-text-block.jsx
> +import { Planet } from "components";
поправил

2022-08-16 13:56 UTC, SergeiKolesnikovAdd commented on components/sections/intro-about-text-block/intro-about-text-block.style.js
> +  ${getCurrentMarginStyle("right", "xxsm")};
поправил

2022-08-16 13:56 UTC, SergeiKolesnikovAdd commented on components/sections/intro-main-text-block/intro-main-text-block.style.js
> +    span {
поправил

2022-08-16 13:56 UTC, SergeiKolesnikovAdd commented on components/sections/intro-main-text-block/intro-main-text-block.style.js
> +   span {
поправил

2022-08-16 13:56 UTC, SergeiKolesnikovAdd commented on components/sections/intro-main-text-block/intro-main-text-block.style.js
> +   span {
поправил

2022-08-16 14:00 UTC, SergeiKolesnikovAdd commented on components/index.js
> +// import { RunningLine } from "./common/running-line";
почистил

2022-08-16 14:00 UTC, SergeiKolesnikovAdd commented on components/index.js
> +  // CloseButton,
полечил

2022-08-16 14:00 UTC, SergeiKolesnikovAdd commented on components/index.js
> +  // DetailCardModal,
полечил

2022-08-16 16:30 UTC, Leroyjs requested changes

2022-08-16 16:30 UTC, Leroyjs commented on components/common/left-bracket/left-bracket.jsx
> +        stroke-width="2"
не поправил

2022-08-16 16:30 UTC, Leroyjs commented on components/common/right-bracket/right-bracket.jsx
> +        stroke-width="2"
проблема

2022-08-16 16:30 UTC, Leroyjs commented on components/sections/intro-main-text-block/intro-main-text-block.style.js
> +export const StyledWhiteH2 = styled(H2)`
если нужен цвет, то ты можешь просто передать туда параметр color="white".
сча уже не нужно, но на будущее

2022-08-16 16:34 UTC, SergeiKolesnikovAdd commented on components/common/left-bracket/left-bracket.jsx
> +        stroke-width="2"
поправил

2022-08-16 16:34 UTC, SergeiKolesnikovAdd commented on components/common/right-bracket/right-bracket.jsx
> +        stroke-width="2"
поправил

2022-08-16 16:35 UTC, merged