Feature/shop
Leroyjs/color-department pull request #26
Opened 2022-08-14 19:35 UTC by Gruzdov-code

Вся страничка шопа

2022-08-14 20:28 UTC, Leroyjs requested changes

2022-08-14 20:28 UTC, Leroyjs commented on components/common/shop-item/shop-item.style.js
> +import { H3 } from "components";
один импорт!

2022-08-14 20:28 UTC, Leroyjs commented on components/common/shop-item/shop-item.style.js
> +  color: ${colors.red};
откуда красный цвет?

2022-08-14 20:28 UTC, Leroyjs commented on components/common/shop-item/shop-item.style.js
> +  transition: 0.3s;
задавай конкретному свойству транзишн, а не всем свойствам!
Это может привести к ненужным анимациям при перезагрузке страницы

2022-08-14 20:28 UTC, Leroyjs commented on components/common/shop-item/shop-item.style.js
> +  /* padding: 32px 40px; */
комменты удаляй

2022-08-14 20:28 UTC, Leroyjs commented on components/common/shop-item/shop-item.style.js
> +  span {
тут лучше перенос ебануть

2022-08-14 20:28 UTC, Leroyjs commented on components/common/shop-item/shop-item.style.js
> +  &:hover {
тут тоже перенос

2022-08-14 20:28 UTC, Leroyjs commented on components/common/shop-item/shop-item.style.js
> +    transition:0.3s;
транзишн конкретному свойству, а не всем

2022-08-14 20:28 UTC, Leroyjs commented on components/common/shop-item/shop-item.style.js
> +    button {
перенос перед теком

2022-08-14 20:28 UTC, Leroyjs commented on components/common/shop-item/shop-item.style.js
> +      &:hover {
перенос перед ховером

2022-08-14 20:28 UTC, Leroyjs commented on components/common/shop-item/shop-item.style.js
> +      transition:0.3s;
транзишн....

2022-08-14 20:28 UTC, Leroyjs commented on components/common/shop-item/shop-item.style.js
> +      div {
перенос

2022-08-14 20:28 UTC, Leroyjs commented on components/common/shop-item/shop-item.style.js
> +
тут удалить перенос

2022-08-14 20:28 UTC, Leroyjs commented on components/common/shop-item/shop-item.style.js
> +        transition:0.3s;
транзишн нужным свойствам, а не всем!

2022-08-14 20:28 UTC, Leroyjs commented on components/common/shop-item/shop-item.style.js
> +      h3 {
перенос перед тегом

2022-08-14 20:28 UTC, Leroyjs commented on components/common/shop-item/shop-item.style.js
> +    span {
перенос

2022-08-14 20:28 UTC, Leroyjs commented on components/common/shop-item/shop-item.style.js
> +    h3 {
перенос

2022-08-14 20:28 UTC, Leroyjs commented on components/common/shop-item/shop-item.style.js
> +        color: ${({ theme }) => getCurrentColor("black", theme)};
для колора есть отдельна функция которая задает колор

2022-08-14 20:28 UTC, Leroyjs commented on components/common/shop-item/shop-item.style.js
> +        color: ${({ theme }) => getCurrentColor("white", theme)};
для колора есть отдельна функция которая задает колор

2022-08-14 20:28 UTC, Leroyjs commented on components/common/shop-item/shop-item.style.js
> +// export const ProductName = styled.h3`
чистим за собой

2022-08-14 20:28 UTC, Leroyjs commented on components/common/shop-item/shop-item.style.js
> +//   ${getCurrentColorStyles("white")};
чистим за собой

2022-08-14 20:28 UTC, Leroyjs commented on components/common/shop-item/shop-item.style.js
> +//   ${getCurrentPaddingStyle("Top", "32px")};
чистим за собой

2022-08-14 20:28 UTC, Leroyjs commented on components/common/shop-item/shop-item.style.js
> +//   text-transform: uppercase;
чистим за собой

2022-08-14 20:28 UTC, Leroyjs commented on components/common/shop-item/shop-item.style.js
> +export const ProductImage = styled.div`
перенос

2022-08-14 20:28 UTC, Leroyjs commented on components/common/shop-modal/shop-modal.jsx
> +import { Input } from "components";
в один импорт

2022-08-14 20:28 UTC, Leroyjs commented on components/common/shop-modal/shop-modal.jsx
> +import { observer } from "mobx-react-lite";
зачем тут обсервер?

2022-08-14 20:28 UTC, Leroyjs commented on components/common/shop-modal/shop-modal.jsx
> +
это что за разрыв?

2022-08-14 20:28 UTC, Leroyjs commented on components/common/shop-modal/shop-modal.jsx
> +    const SelectSizeOptions = [
Для констант создаем отдельный файл constants.js и импортим из него

2022-08-14 20:28 UTC, Leroyjs commented on components/common/shop-modal/shop-modal.jsx
> +    const SelectSizeOptions = [
Почему имя обычной константы с большой буквы?

2022-08-14 20:28 UTC, Leroyjs commented on components/common/shop-modal/shop-modal.jsx
> +
что за разрыв?

2022-08-14 20:28 UTC, Leroyjs commented on components/common/shop-modal/shop-modal.jsx
> +              <Input
если компонент не имеет детей, то лучше делать его самозакрывающим. Тут много проблем с этим, пробегись плз по всему коду

2022-08-14 20:28 UTC, Leroyjs commented on components/common/shop-modal/shop-modal.style.js
> +import { getCurrentPaddingStyle } from "styles";
ну ты сам понял про импорты

2022-08-14 20:28 UTC, Leroyjs commented on components/common/shop-modal/shop-modal.style.js
> +width:50%;
где таб?

2022-08-14 20:28 UTC, Leroyjs commented on components/common/shop-modal/shop-modal.style.js
> +
что за разрыв?

2022-08-14 20:28 UTC, Leroyjs commented on components/common/shop-modal/shop-modal.style.js
> +  /* ${({ theme }) => getCurrentBackgroundColorStyles("black", theme)}; */
комменты удаляем

2022-08-14 20:28 UTC, Leroyjs commented on components/common/shop-modal/shop-modal.style.js
> +display:flex;
табыыыыы

2022-08-14 20:28 UTC, Leroyjs commented on components/common/shop-modal/shop-modal.style.js
> +justify-content:space-between;
установи преттер плз)

2022-08-14 20:28 UTC, Leroyjs commented on components/common/shop-modal/shop-modal.style.js
> +export const ProductName = styled(H3)``;
в чем смысл этой стилизации?)

2022-08-14 20:28 UTC, Leroyjs commented on components/sections/dist/shop-section.style.dev.js
> +
дисты удаляй

2022-08-14 20:28 UTC, Leroyjs commented on components/sections/shop-section.jsx
> +  const arrShopTest = [
константы в отдельный файл или пиши, что это тестовые данные

2022-08-14 20:28 UTC, Leroyjs commented on components/sections/shop-section.jsx
> +  return (
перед ретерн перенос почти всегда должен быть

2022-08-14 20:28 UTC, Leroyjs commented on components/sections/shop-section.jsx
> +
это что за перенос?

2022-08-14 20:28 UTC, Leroyjs commented on components/sections/shop-section.jsx
> +  let shopList = arrShopTest.map((item) => (
Можно деструктуризировать
Не пиши итем, это всеравно ни о чем не говорит
Пиши { title, id, cost, img }

2022-08-14 20:28 UTC, Leroyjs commented on components/sections/shop-section.style.js
> +  /* ${getCurrentGridTemplateColumsStyle()}; */
чисти комменты

2022-08-14 20:28 UTC, Leroyjs commented on components/ui/button-exit/button-exit.jsx
> +
это что за перенос?

2022-08-14 20:28 UTC, Leroyjs commented on components/ui/button-exit/button-exit.style.js
> +
это шо за перенос?

2022-08-14 20:28 UTC, Leroyjs commented on components/ui/button-exit/button-exit.style.js
> +import { getCurrentMarginStyle } from "styles";
один импорт

2022-08-14 20:28 UTC, Leroyjs commented on components/ui/button-exit/button-exit.style.js
> +
что за технологическое отверстие?

2022-08-14 20:28 UTC, Leroyjs commented on components/ui/button-shop/button-shop.jsx
> +
тут же импорты заебись

2022-08-14 20:28 UTC, Leroyjs commented on components/ui/button-shop/button-shop.jsx
> +		<PlusLineVertical />
куда его понесло?
Юзай преттер!!!!!!!!!!!!!!!!

2022-08-14 20:28 UTC, Leroyjs commented on components/ui/button-shop/button-shop.style.js
> +
тут 1 должен быть, а не 2 переноса

2022-08-14 20:28 UTC, Leroyjs commented on components/ui/button-shop/button-shop.style.js
> +  /* display: inline-block ; */
чистим

2022-08-14 20:28 UTC, Leroyjs commented on components/ui/button-shop/button-shop.style.js
> +	transform: rotate(90deg);
куда понесло?

2022-08-14 20:28 UTC, Leroyjs commented on components/ui/counter/counter.jsx
> +
ненужный перенос

2022-08-14 20:28 UTC, Leroyjs commented on components/ui/counter/counter.jsx
> +  function increment() {
а тут переноса почему то нет

2022-08-14 20:28 UTC, Leroyjs commented on components/ui/counter/counter.jsx
> +    const newValueDec = --value;
этим действием ты уменьшаешь значение value напрямую, а нужно через onChange.
Должно быть так:
   const newValueDec = value - 1;

2022-08-14 20:28 UTC, Leroyjs commented on components/ui/counter/counter.jsx
> +    const newValueInc = ++value;
тут такая же хуйня

2022-08-14 20:28 UTC, Leroyjs commented on components/ui/counter/counter.jsx
> +
перенос

2022-08-14 20:28 UTC, Leroyjs commented on components/ui/counter/counter.jsx
> +      <InputStyled
соло тег

2022-08-14 20:28 UTC, Leroyjs commented on components/ui/counter/counter.jsx
> +      <Minus onClick={() => decrement()}></Minus>
нахуя создавайть функцию с оберткой функции?

2022-08-14 20:28 UTC, Leroyjs commented on components/ui/counter/counter.style.js
> +const errorConditionColor = ({ isError }) =>
после импортов перенос

2022-08-14 20:28 UTC, Leroyjs commented on components/ui/counter/counter.style.js
> +const errorConditionBackgroundColor = ({ isError }) =>
тут тоже перенос

2022-08-14 20:28 UTC, Leroyjs commented on components/ui/counter/counter.style.js
> +      return { stroke: colors.yellow };
точно yellow, а не праймари?

2022-08-14 20:28 UTC, Leroyjs commented on components/ui/counter/counter.style.js
> +  &:hover {
перенос

2022-08-14 20:28 UTC, Leroyjs commented on components/ui/minus/dist/minus.style.dev.js
> +Object.defineProperty(exports, "__esModule", {
чистим

2022-08-14 20:28 UTC, Leroyjs commented on components/ui/minus/minus.jsx
> +      ;
зачем тут ; ?

2022-08-14 20:28 UTC, Leroyjs commented on components/ui/minus/minus.style.js
> +      return { stroke: colors.yellow };
мне кажется, или код дублируется?

2022-08-14 20:28 UTC, Leroyjs commented on components/ui/minus/minus.style.js
> +      return { stroke: colors.yellow };
если да, то вынеси в отдельную функцию

2022-08-14 20:28 UTC, Leroyjs commented on components/ui/plus/plus.jsx
> +      ;
ну ты понял

2022-08-14 20:28 UTC, Leroyjs commented on components/ui/plus/plus.style.js
> +      return { stroke: colors.yellow };
ну ты тут тоже понял

2022-08-14 20:28 UTC, Leroyjs commented on components/ui/plus/plus.style.js
> +  :hover {
что?
Он же не работает

2022-08-14 20:28 UTC, Leroyjs commented on pages/modal-shop-test.js
> +			<ShopModal isOpen={true} />
оооох, куда понесло

2022-08-14 20:28 UTC, Leroyjs commented on pages/shop.js
> +	</>
тож пизда по форматированию

2022-08-14 20:28 UTC, Leroyjs commented on pages/shop.js
> +import { RunningLine } from "components";
ну ты понял, импорты

2022-08-14 20:28 UTC, Leroyjs commented on styles/constants.js
> +    xsm: 12 ,
зачем тут пробел?

2022-08-14 20:28 UTC, Leroyjs commented on styles/get-styles-utils.js
> +export const getCurrentColorStrokeStyles = (color, theme) =>
лайк за функцию, но перенос забыл

2022-08-14 20:28 UTC, Leroyjs commented on styles/get-styles-utils.js
> +    // `repeat(${countDesktopLG}, ${x1DesktopLG})`,
чисти

2022-08-14 20:28 UTC, Leroyjs commented on .vscode/settings.json
> +  "compile-hero.disable-compile-files-on-did-save-code": false
БОГА РАДИ УСТАНОВИ ПРЕТТЕР!!!!!!!!!!!!!!!!!

2022-08-15 09:32 UTC, Gruzdov-code commented on components/common/shop-item/dist/shop-item.style.dev.js
> +"use strict";
исправлено

2022-08-15 09:32 UTC, Gruzdov-code commented on components/common/shop-item/shop-item.jsx
> +import { ShopModal } from "components";
исправлено

2022-08-15 09:32 UTC, Gruzdov-code commented on components/common/shop-item/shop-item.jsx
> +
переносы чего?

2022-08-15 09:34 UTC, Leroyjs commented on components/common/shop-item/shop-item.jsx
> +
enter

2022-08-15 11:20 UTC, Gruzdov-code commented on components/common/shop-item/shop-item.jsx
> +      <ShopModal title={title} cost={cost} img={img} setOpen={(e) => {handlerClose(e)}} isOpen={open}></ShopModal>
исправлено

2022-08-16 06:31 UTC, Gruzdov-code commented on components/common/shop-item/shop-item.jsx
> +      <ShopModal title={title} cost={cost} img={img} setOpen={(e) => {handlerClose(e)}} isOpen={open}></ShopModal>
исправлено

2022-08-16 06:33 UTC, Gruzdov-code commented on components/common/shop-item/shop-item.style.js
> +import { getCurrentColor } from "styles";
исправлено

2022-08-16 06:33 UTC, Gruzdov-code commented on components/common/shop-item/shop-item.style.js
> +import { H3 } from "components";
исправлено

2022-08-16 06:34 UTC, Gruzdov-code commented on components/common/shop-item/shop-item.style.js
> +  color: ${colors.red};
исправлено

2022-08-17 07:43 UTC, Leroyjs requested changes

2022-08-17 07:43 UTC, Leroyjs commented on components/common/shop-modal/shop-modal.jsx
> +              console.log(e);
что за логирование? Когда кидаем пр, удаляем

2022-08-17 09:41 UTC, Gruzdov-code commented on pages/shop.js
> +import { RunningLine } from "components";
исправлено

2022-08-17 09:42 UTC, Gruzdov-code commented on styles/constants.js
> +    xsm: 12 ,
исправлено

2022-08-17 09:42 UTC, Gruzdov-code commented on styles/get-styles-utils.js
> +export const getCurrentColorStrokeStyles = (color, theme) =>
исправлено

2022-08-17 09:42 UTC, Gruzdov-code commented on styles/get-styles-utils.js
> +    // `repeat(${countDesktopLG}, ${x1DesktopLG})`,
исправлено

2022-08-17 09:43 UTC, Gruzdov-code commented on .vscode/settings.json
> +  "compile-hero.disable-compile-files-on-did-save-code": false
исправлено

2022-08-17 09:44 UTC, Gruzdov-code commented on components/common/shop-modal/shop-modal.jsx
> +              console.log(e);
исправлено

2022-08-17 10:40 UTC, Gruzdov-code commented on components/common/shop-item/shop-item.style.js
> +  transition: 0.3s;
исправлено

2022-08-17 10:51 UTC, Gruzdov-code commented on components/common/shop-item/shop-item.style.js
> +  /* padding: 32px 40px; */
исправлено

2022-08-17 10:52 UTC, Gruzdov-code commented on components/common/shop-item/shop-item.style.js
> +  span {
исправлено

2022-08-17 10:52 UTC, Gruzdov-code commented on components/common/shop-item/shop-item.style.js
> +  &:hover {
исправлено

2022-08-17 10:54 UTC, Gruzdov-code commented on components/common/shop-item/shop-item.style.js
> +    transition:0.3s;
там конкретно всем нужно, т.к надо не при наведении на него делать транзишн а при наведении на общую карточку,

2022-08-17 10:55 UTC, Gruzdov-code commented on components/common/shop-item/shop-item.style.js
> +    transition:0.3s;
но убрал лишние на ховеры этих элементов

2022-08-17 10:59 UTC, Gruzdov-code commented on components/common/shop-item/shop-item.style.js
> +    h3 {
исправлено

2022-08-17 10:59 UTC, Gruzdov-code commented on components/common/shop-item/shop-item.style.js
> +    span {
исправлено

2022-08-17 11:00 UTC, Gruzdov-code commented on components/common/shop-item/shop-item.style.js
> +      h3 {
исправлено

2022-08-17 11:00 UTC, Gruzdov-code commented on components/common/shop-item/shop-item.style.js
> +        transition:0.3s;
отписал выше

2022-08-17 11:06 UTC, Gruzdov-code commented on components/common/shop-item/shop-item.style.js
> +    button {
исправлено

2022-08-17 11:06 UTC, Gruzdov-code commented on components/common/shop-item/shop-item.style.js
> +      &:hover {
исправлено

2022-08-17 11:06 UTC, Gruzdov-code commented on components/common/shop-item/shop-item.style.js
> +      div {
исправлено

2022-08-17 11:07 UTC, Gruzdov-code commented on components/common/shop-item/shop-item.style.js
> +
исправлено

2022-08-17 11:07 UTC, Gruzdov-code commented on components/common/shop-item/shop-item.style.js
> +        color: ${({ theme }) => getCurrentColor("black", theme)};
исправлено

2022-08-17 11:07 UTC, Gruzdov-code commented on components/common/shop-item/shop-item.style.js
> +        color: ${({ theme }) => getCurrentColor("white", theme)};
исправлено

2022-08-17 11:07 UTC, Gruzdov-code commented on components/common/shop-item/shop-item.style.js
> +// export const ProductName = styled.h3`
исправлено

2022-08-17 11:07 UTC, Gruzdov-code commented on components/common/shop-item/shop-item.style.js
> +//   ${getCurrentColorStyles("white")};
исправлено

2022-08-17 11:07 UTC, Gruzdov-code commented on components/common/shop-item/shop-item.style.js
> +//   ${getCurrentPaddingStyle("Top", "32px")};
исправлено

2022-08-17 11:08 UTC, Gruzdov-code commented on components/common/shop-item/shop-item.style.js
> +//   text-transform: uppercase;
исправлено

2022-08-17 11:08 UTC, Gruzdov-code commented on components/common/shop-item/shop-item.style.js
> +export const ProductImage = styled.div`
исправлено

2022-08-17 11:09 UTC, Gruzdov-code commented on components/common/shop-modal/shop-modal.jsx
> +import { Input } from "components";
исправлено

2022-08-17 15:37 UTC, Gruzdov-code commented on components/common/shop-item/shop-item.style.js
> +      transition:0.3s;
отписал выше

2022-08-17 15:38 UTC, Gruzdov-code commented on components/common/shop-modal/shop-modal.jsx
> +
исправил

2022-08-17 15:42 UTC, Gruzdov-code commented on components/common/shop-modal/shop-modal.jsx
> +    const SelectSizeOptions = [
исправил

2022-08-17 15:42 UTC, Gruzdov-code commented on components/common/shop-modal/shop-modal.jsx
> +    const SelectSizeOptions = [
исправил

2022-08-17 15:45 UTC, Gruzdov-code commented on components/common/shop-modal/shop-modal.style.js
> +import { getCurrentPaddingStyle } from "styles";
исправлено

2022-08-17 15:47 UTC, Gruzdov-code commented on components/common/shop-modal/shop-modal.style.js
> +width:50%;
исправлено

2022-08-17 15:47 UTC, Gruzdov-code commented on components/common/shop-modal/shop-modal.style.js
> +
исправлено

2022-08-17 15:47 UTC, Gruzdov-code commented on components/common/shop-modal/shop-modal.style.js
> +display:flex;
исправлено

2022-08-17 15:48 UTC, Gruzdov-code commented on components/common/shop-modal/shop-modal.style.js
> +justify-content:space-between;
исправлено

2022-08-19 19:23 UTC, merged