Feature/header
Leroyjs/color-department pull request #6
Opened 2022-07-31 20:35 UTC by Kaigarodov

2022-08-01 06:12 UTC, Leroyjs commented
This branch has conflicts that must be resolved
Use the [web editor](https://github.com/Leroyjs/color-department/pull/6/conflicts) or the  to resolve conflicts.
Conflicting files
components/index.js
pages/index.js

2022-08-01 06:51 UTC, Leroyjs requested changes

2022-08-01 06:51 UTC, Leroyjs commented on components/common/blob/blob.style.js
> +    &:hover {cursor: pointer;}
Лучше сделать чтобы cursor: pointer был даже без ховера? Это по сути одно и тоже, но так меньше кода

2022-08-01 06:51 UTC, Leroyjs commented on components/common/google-map/google-map.jsx
> +}
мапу пока что не ревьюю

2022-08-01 06:51 UTC, Leroyjs commented on components/common/humburger/humburger.jsx
> +export const Hamburger = ({ ...props }) => (
Ему бы сделать пропс isActive/isOpen/isClose итд который бы управлял его состоянием когда он имеет вид бургера и когда он имеет вид крестика

2022-08-01 06:51 UTC, Leroyjs commented on components/common/humburger/humburger.jsx
> +export const Hamburger = ({ ...props }) => (
И ты пропсы объявил, но не используешь их

2022-08-01 06:51 UTC, Leroyjs commented on components/common/humburger/humburger.jsx
> +export const Hamburger = ({ ...props }) => (
({isActive, onClick, ...props})
<HumburgerWrapper isActive={isActive} onClick={onClick} {...props}>

Желательно деструктуризировать пропсы так, чтобы явно показать что компонент принимает 2 пропса (isActive, onClick). 
Я понимаю, что этот компонент будет использоваться только в 1 месте, это скорее просто показать на будущее.

2022-08-01 06:51 UTC, Leroyjs commented on components/common/humburger/humburger.style.js
> +  &:hover {transform: rotate(90deg);}
не забудь удалить

2022-08-01 06:51 UTC, Leroyjs commented on components/common/humburger/humburger.style.js
> +  background-color: white;
Цвет лучше брать из colors

2022-08-01 06:51 UTC, Leroyjs commented on components/sections/header/header.jsx
> +import { Blob, Hamburger } from "../../common";
components/common
Возможно так будет лучше?

2022-08-01 06:51 UTC, Leroyjs commented on components/sections/header/header.jsx
> +import theme from '../../../__data__/theme';
У нас есть элиасы "__data__/theme"

2022-08-01 06:51 UTC, Leroyjs commented on components/sections/header/header.jsx
> +import theme from '../../../__data__/theme';
Только посмотри плз элиасы в jsconfig

2022-08-01 06:51 UTC, Leroyjs commented on components/sections/header/header.jsx
> +  const [toggleMenu, setToggleMenu] = useState(false);
мб лучше дать более понятное название? toggleMenu дает понимание что это как то связано с меню, но не дает понимание открыто ли меню, если мы знаем его значение)

toggleMenu звучит как функция которая переключает значение, а не хранит состояние)

Возможно стоит переименовать его на IsBurgerMenuOpen?

2022-08-01 06:51 UTC, Leroyjs commented on components/sections/header/header.jsx
> +      return () => { window.removeEventListener('scroll', scrollListener) }
Круто что не забыл снять событие!

2022-08-01 06:51 UTC, Leroyjs commented on components/sections/header/header.jsx
> +        <Caption color={'white'}>Lets talk</Caption>
можно просто писать color='white' без динамики

2022-08-01 06:51 UTC, Leroyjs commented on components/sections/header/header.jsx
> +      <HeaderItem m={true} hover={true} {...props}>
m={true}?
Что это значит?

2022-08-01 06:51 UTC, Leroyjs commented on components/sections/header/header.style.js
> +    z-index: -1;
нужно будет создать в файле styles/constants.js объект с z-index 
e.g. zIndex = {
modal: 1000
header: 100
frontItem: 10 
backItem: -1
}

2022-08-01 06:51 UTC, Leroyjs commented on components/sections/header/header.style.js
> +    background-color: ${hexToRGBA(colors.black, 1)};
Не совсем понимаю зачем тут переводить в RGBA если мы используем альфа канал как 1

2022-08-01 06:51 UTC, Leroyjs commented on components/sections/header/header.style.js
> +  color: white;
Лучше брать цвет из colors

2022-08-01 06:51 UTC, Leroyjs commented on components/sections/header/header.style.js
> +    line-height: 112%;
Разве в UI компоненте не прописан line-height?
Если не прописан, то нужно пингануть Серегу

2022-08-01 06:51 UTC, Leroyjs commented on components/sections/header/header.style.js
> +    .humburger-btn {
пустые лучше удалять

2022-08-01 06:51 UTC, Leroyjs commented on components/sections/header/header.style.js
> +  transition : background-color 0.5s, color 0.5s;
Круто что прописываешь какие свойства анимируются!
Я про то что ты пишешь каждому свойству отдельно а не пишешь transition: 0.5s)

2022-08-01 06:51 UTC, Leroyjs commented on components/sections/index.js
> +export * from './header';
нам не нужно все, нам нужно только Header

2022-08-01 06:51 UTC, Leroyjs commented on components/sections/menu/menu.jsx
> +export const Menu = (props) => {
Лучше ставить перенос после импортов

2022-08-01 06:51 UTC, Leroyjs commented on components/sections/menu/menu.style.js
> +
что то оч много переносов)

2022-08-01 06:51 UTC, Leroyjs commented on components/sections/menu/menu.style.js
> +    background-color: blue;
Понимаю, что заглушка)
на всякий случай напоминаю про цвета из colors)

2022-08-01 06:51 UTC, Leroyjs commented on pages/index.js
> +  const changeMenuState = (newMenuState) => {
Эту логику лучше не выносить за пределы хедера

2022-08-01 06:51 UTC, Leroyjs commented on pages/index.js
> +      <Menu isOpen={isOpenMenu}></Menu>
мы сможем меню в хэадер засунуть?

2022-08-01 06:51 UTC, Leroyjs commented on pages/index.js
> +
А вообще заебись!
Если ты первый раз с реактом работаешь, то вообще круто! =)

2022-08-02 17:51 UTC, igorTyugaev commented on components/common/blob/blob.jsx
> +            <svg width="20" height="28" viewBox="0 0 20 28" fill="none" xmlns="http://www.w3.org/2000/svg" {...props}>
Перед вставкой SVG в разметку его надо прогнать через [SVGOMG](https://jakearchibald.github.io/svgomg/) это значительно уменьшит вес изображения и уберет ненужные атрибуты из разметки.

В частности тут совершенно не уместен атрибут xmlns="http://www.w3.org/2000/svg и через мерно высокая точность 18.6667C20

2022-08-02 17:51 UTC, igorTyugaev commented on components/common/blob/blob.style.js
> +    &:hover {cursor: pointer;}
Мб, лучше сразу задать блоку нужный тип курсора cursor: pointer; Чтобы при ховере искл. вероятность мерцания этого курсора из-за перекл. его типа

2022-08-02 17:51 UTC, igorTyugaev commented on components/common/fox-paw/fox-paw.style.js
> +    transform: ${true ? " translateX(0px)" : ""};
Ой, а что это. Кажется хотели сделать какой-то параметр, а потом передумали? 

Лучше тогда свернуть к виду: transform: translateX(0px)

Или все же обработать условие?

2022-08-02 17:51 UTC, igorTyugaev commented on components/common/google-map/google-map.jsx
> +            let map = new google.maps.Map(mapRef);
В данном случае переменная map хранить экземпляр класса (ссылочный тип), поэтому уместнее использовать все-таки const. Да и вообще мы юзаем везде const, если ситуации не просить let.

Очень вряд ли там надо передавать саму рефу Map(mapRef) скорее её содержимое Map(mapRef.current)

2022-08-02 17:51 UTC, igorTyugaev commented on components/sections/header/header.jsx
> +  const onHumburgerClick = () => {
Нихуя подобного. Если уж и зашел разговор про оптимизацию, то лучше их вынести из функции тогда. Но это может создать определенный гемор.

Для данного примитивного случая useCallback только снизить производительность)))

Пруфы тут
https://www.youtube.com/watch?v=2Wp7QPTkpms

2022-08-02 17:51 UTC, igorTyugaev commented on components/sections/header/header.jsx
> +    setToggleMenu(newToggleState);
setState() это асинхронная функция. В целом данная конструкция не корректная.
Вернее было бы написать setToggleMenu(prevState => !prevState); 

Смотри как работать с хуком useSate()

https://www.youtube.com/watch?v=hQRPsKzpo34

2022-08-02 17:51 UTC, igorTyugaev commented on components/sections/header/header.jsx
> +      const scrollListener = () => {
Скролл спамит своими событиями. Подумай об использовании дебаунсера для этого обработчика скролла. Чтобы вызывал не чаше чем раз в 10 мс

2022-08-02 17:51 UTC, igorTyugaev commented on components/sections/header/header.jsx
> +      const scrollListener = () => {
Читать тут Декоратор debounce
https://learn.javascript.ru/task/debounce

2022-08-02 17:51 UTC, igorTyugaev commented on components/sections/header/header.jsx
> +        <HeaderItem l={true}>
что за  l

2022-08-02 17:51 UTC, igorTyugaev commented on components/sections/header/header.jsx
> +        <HeaderItem m={true} hover={true} {...props}>
что за m?

2022-08-02 17:51 UTC, igorTyugaev commented on components/sections/header/header.jsx
> +        <HeaderItem m={true} hover={true} {...props}>
переменные bool типа должны начинаться с префикса  is или  has.

соотвественно не hover, a isHover

2022-08-02 17:51 UTC, igorTyugaev commented on components/sections/header/header.style.js
> +    content:"";
А вы уверены, что это у вас работает? 
В emotion есть такой прикол, что надо писать content: '""';  Или не всегда, крч если будут проблемы попробуйте так...)

2022-08-02 17:51 UTC, igorTyugaev commented on components/sections/header/header.style.js
> +export const Title = styled.div`
А зачем тут вообще спан оказался внутри дива и почему селектор тега?

2022-08-02 17:51 UTC, igorTyugaev commented on pages/index.js
>                      console.log(val)
Удаляем за собой  console.log -и перед коммитом

2022-08-02 17:51 UTC, igorTyugaev commented on styles/map.js
> +]
Красавчик че, можешь купить себе пивка!

2022-08-02 18:05 UTC, Leroyjs requested changes

2022-08-02 18:05 UTC, Leroyjs commented on components/sections/header/header.jsx
> +  const onHumburgerClick = () => {
Колбек как раз таки нужно использовать не для мемоизации ради мемоизации, а для того чтобы исключить постоянный перерендер компонента когда передаешь колбек как пропс. В данном случае он как раз и передается как пропс. И сейчас если поменяется хэдер, то и перерендерится компонент куда передается этот колбек

2022-08-03 21:58 UTC, Kaigarodov commented on components/sections/header/header.style.js
> +    content:"";
хз, может что-то пропустил, но я заюзал content : "", без него before/after не отображаются же)

2022-08-03 22:13 UTC, Kaigarodov commented on components/sections/header/header.jsx
> +        <HeaderItem l={true}>
гриды еще не использовали, делал временное решение

2022-08-04 19:30 UTC, Kaigarodov commented on components/sections/header/header.jsx
> +      <HeaderItem l={true}>
заглушка, уже брал

2022-08-04 19:44 UTC, Kaigarodov commented on components/common/google-map/google-map.jsx
> +            let map = new google.maps.Map(mapRef);
мапу отдали под другое крыло

2022-08-08 19:11 UTC, merged